name: webhook
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=${NODE_VERSION}
    image: rpontual/webhook:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./update_tech_blog.sh:/app/update_tech_blog.sh
    restart: unless-stopped
    ports:
      - ${EXTERNAL_PORT}:80
    environment:
      PATH_TO_PROJECT: ${PATH_TO_PROJECT}
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
